pipeline { 
    agent any 
    stages {
        stage('Build') { 
            steps {
                    echo "Sample scipt "
                }
            }
        
        stage('Second'){
            steps {
                    input "do you want to proceed ?"
                }

            }
       
        stage('Deploy') {
            steps {
               withMaven(maven : 'apache-maven-3.3.9'){
                        bat "mvn deploy"
                }

            }
        }
    }
}
