pipeline { 
    agent any 
    stages {
        stage('Build') { 
            steps {
                    echo "Sample scipt "
                }
            }
        
        stage('Second'){
            steps {
                    input "do you want to proceed ?"
                }

            }
       
        stage('Deploy') {
           when
            {
                not
                {
                    branch "master"
                }

            }
            steps
            {
                echo "hello"
            }
            
        }
    }
}
